#!/usr/bin/env bash
# Open a PR against the Homebrew tap (NuttapongPun/homebrew-tap) that bumps the scrub cask to a
# released version. The cask's source of truth lives in the tap repo, NOT here — this script just
# syncs version + SHA256 after a `v*` tag has produced a GitHub Release (issue #14).
#
# Usage:
#   scripts/update-cask.sh [vX.Y.Z]     # default: latest release of this repo
#
# It downloads the release zip, computes its SHA256 (rather than trusting the notes), rewrites the
# `version`/`sha256` lines in the tap's Casks/scrub.rb on a fresh branch, and opens a PR. You review
# and merge. Branch protection on the tap blocks direct pushes, so PR is the only path in.
#
# Requires the `gh` CLI authenticated with push access to the tap repo.
set -euo pipefail

REPO="NuttapongPun/scrub"
TAP_REPO="NuttapongPun/homebrew-tap"

TAG="${1:-$(gh release view --repo "$REPO" --json tagName -q .tagName)}"
VERSION="${TAG#v}"
ZIP="Scrub-${TAG}.zip"
URL="https://github.com/${REPO}/releases/download/${TAG}/${ZIP}"
BRANCH="scrub-${VERSION}"

echo "Syncing tap cask to ${TAG} …"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# Verify the checksum ourselves from the actual asset.
curl -fsSL "$URL" -o "$TMP/$ZIP"
SHA="$(shasum -a 256 "$TMP/$ZIP" | awk '{print $1}')"
echo "  version = $VERSION"
echo "  sha256  = $SHA"

CLONE="$TMP/tap"
gh repo clone "$TAP_REPO" "$CLONE" -- --depth 1
CASK="$CLONE/Casks/scrub.rb"
[[ -f "$CASK" ]] || { echo "error: $CASK not found in tap repo" >&2; exit 1; }

# Rewrite the two pinned lines (BSD/macOS sed).
sed -i '' -E "s/^( *version )\"[^\"]*\"/\1\"${VERSION}\"/" "$CASK"
sed -i '' -E "s/^( *sha256 )\"[^\"]*\"/\1\"${SHA}\"/" "$CASK"

if git -C "$CLONE" diff --quiet; then
  echo "Tap already at ${VERSION}; nothing to do."
  exit 0
fi

COMMIT_MSG="chore(cask): bump scrub to ${VERSION}"
git -C "$CLONE" switch -c "$BRANCH"
git -C "$CLONE" commit -am "$COMMIT_MSG"
git -C "$CLONE" push -u origin "$BRANCH"
gh pr create --repo "$TAP_REPO" \
  --base main --head "$BRANCH" \
  --title "$COMMIT_MSG" \
  --body "Bump scrub cask to \`${VERSION}\` from release [${TAG}](https://github.com/${REPO}/releases/tag/${TAG}).

- version: \`${VERSION}\`
- sha256: \`${SHA}\`

Generated by \`scripts/update-cask.sh\`."
echo "Opened PR against ${TAP_REPO}. Review and merge to publish."
